services:
  comet:
    image: g0ldyy/comet
    restart: unless-stopped

    environment:
      DATABASE_TYPE: postgresql
      DATABASE_URL: postgresql://comet:comet@postgres:5432/comet

    env_file:
      - .env

    volumes:
      - comet_data:/app/data

    expose:
      - "8000"

    depends_on:
      postgres:
        condition: service_started


  postgres:
    image: postgres:18-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: comet
      POSTGRES_PASSWORD: comet
      POSTGRES_DB: comet

    volumes:
      - postgres_data:/var/lib/postgresql/data

    # healthcheck removido intencionalmente para estabilidade no Coolify


volumes:
  comet_data:
  postgres_data:
